<a href="https://colab.research.google.com/github/Sabharishraja/Machine_Learning/blob/main/Multilayer_perceptron_with_back_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
bnotes = pd.read_csv("/content/banknote-authentication.csv")
bnotes.head(10)

variance    skew  curtosis  entropy  class
0   3.62160  8.6661  -2.80730 -0.44699      0
1   4.54590  8.1674  -2.45860 -1.46210      0
2   3.86600 -2.6383   1.92420  0.10645      0
3   3.45660  9.5228  -4.01120 -3.59440      0
4   0.32924 -4.4552   4.57180 -0.98880      0
5   4.36840  9.6718  -3.96060 -3.16250      0
6   3.59120  3.0129   0.72888  0.56421      0
7   2.09220 -6.8100   8.46360 -0.60216      0
8   3.20320  5.7588  -0.75345 -0.61251      0
9   1.53560  9.1772  -2.27180 -0.73535      0

In [4]:
bnotes.describe(include="all")

variance         skew     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [6]:
x = bnotes.drop("class",axis=1)
y = bnotes["class"]
print(x.head(2))
print(y.head(2))

   variance    skew  curtosis  entropy
0    3.6216  8.6661   -2.8073 -0.44699
1    4.5459  8.1674   -2.4586 -1.46210
0    0
1    0
Name: class, dtype: int64


In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
mlp = MLPClassifier(max_iter=500,activation="relu")
mlp.fit(x_train,y_train)

MLPClassifier(max_iter=500)

In [9]:
pred = mlp.predict(x_test)
print(pred)

[1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 0
 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0
 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1]


In [10]:
confusion_matrix(y_test,pred)

array([[148,   0],
       [  0, 127]])

In [11]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [18]:
mlp = MLPClassifier(max_iter=500,activation="logistic")
mlp.fit(x_train,y_train)
pred = mlp.predict(x_test)
print(pred)

[1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 0
 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0
 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1]


In [14]:
confusion_matrix(y_test,pred)

array([[148,   0],
       [  0, 127]])

In [15]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [17]:
mlp = MLPClassifier(max_iter=500,activation="tanh")
mlp.fit(x_train,y_train)
pred = mlp.predict(x_test)
print(pred)

[1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 0
 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0
 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1]


In [19]:
confusion_matrix(y_test,pred)

array([[148,   0],
       [  1, 126]])

In [20]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       148
           1       1.00      0.99      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [22]:
mlp = MLPClassifier(max_iter=500,activation="identity")
mlp.fit(x_train,y_train)

MLPClassifier(activation="identity", max_iter=500)
pred = mlp.predict(x_test)
print(pred)

[1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 0
 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0
 0 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1
 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1]


In [24]:
confusion_matrix(y_test,pred)

array([[147,   1],
       [  3, 124]])

In [25]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       148
           1       0.99      0.98      0.98       127

    accuracy                           0.99       275
   macro avg       0.99      0.98      0.99       275
weighted avg       0.99      0.99      0.99       275



In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
mlp = MLPClassifier(max_iter=500,activation="relu")
mlp.fit(x_train,y_train)
MLPClassifier(max_iter=500)
pred = mlp.predict(x_test)
print(pred)

[0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0
 0 0 0 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0
 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1
 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0
 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0
 0 0 1 1 1]


In [27]:
confusion_matrix(y_test,pred)

array([[236,   0],
       [  0, 176]])

In [28]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       236
           1       1.00      1.00      1.00       176

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412



In [30]:
mlp = MLPClassifier(max_iter=500,activation="logistic")
mlp.fit(x_train,y_train)
MLPClassifier(max_iter=500,activation="logistic")

pred = mlp.predict(x_test)
print(pred)

[0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0
 0 0 0 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0
 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1
 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0
 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0
 0 0 1 1 1]


In [33]:
MLPClassifier(max_iter=500,activation="tanh")

MLPClassifier(activation='tanh', max_iter=500)

In [32]:
confusion_matrix(y_test,pred)

array([[236,   0],
       [  1, 175]])

In [34]:
mlp = MLPClassifier(max_iter=500,activation="tanh")
mlp.fit(x_train,y_train)
pred = mlp.predict(x_test)
print(pred)

[0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0
 0 0 0 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0
 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1
 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 0
 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0
 0 0 1 1 1]


In [35]:
confusion_matrix(y_test,pred)

array([[236,   0],
       [  0, 176]])

In [36]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       236
           1       1.00      1.00      1.00       176

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412



In [37]:
mlp = MLPClassifier(max_iter=500,activation="identity")
mlp.fit(x_train,y_train)
MLPClassifier(max_iter=500,activation="identity")

pred = mlp.predict(x_test)
print(pred)

[0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0
 0 0 0 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0
 1 0 1 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1
 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0
 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0
 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0
 0 0 1 1 1]


In [38]:
confusion_matrix(y_test,pred)

array([[232,   4],
       [  3, 173]])

In [39]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       236
           1       0.98      0.98      0.98       176

    accuracy                           0.98       412
   macro avg       0.98      0.98      0.98       412
weighted avg       0.98      0.98      0.98       412

